#version: 3.7
#
#services:
#  ghost-theme-docker:
#    image: ghost-theme-docker:1.0
#    container_name: ghost-theme-docker
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./.tmp/data:/var/lib/ghost/content/data
#      - ./.tmp/images:/var/lib/ghost/content/images
#      - ./.tmp/settings:/var/lib/ghost/content/settings
#      - ./:/var/lib/ghost/content/themes/dsi
#    ports:
#      - "3102:2368"
#    environment:
#      - NODE_ENV=development   # ← This is the key to success
version: "3.3"
services:
  ghost:
    container_name: ghost
    image: ghost:latest
    restart: always
    ports:
      - "2368:2368"
    depends_on:
      - ghost-db
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__port: 3306
      database__connection__user: mysql
      database__connection__password: mysql
      database__connection__database: ghost
      NODE_ENV: development
    networks:
      - ghost
    volumes:
      - ghost-content:/var/lib/ghost/content

  ghost-db:
    container_name: ghost-db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: ghost
    ports:
      - "3306:3306"
    networks:
        - ghost
    volumes:
      - ghost-mysql:/var/lib/mysql

networks:
    ghost:

volumes:
  ghost-content:
  ghost-mysql:
